name: Format Code

# Run on main and develop branches
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# Set minimal permissions
permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

  # Format check only - removed auto-formatting to prevent security risks
  # Formatting should be done locally and committed by developers
  # This ensures all changes are reviewed before being merged
